//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Implementation.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Incident = new HashSet<Incident>();
            this.UserRequest = new HashSet<UserRequest>();
        }
    
        public long Id { get; set; }
        public string GenReference { get; set; }
        public long TicketTypeId { get; set; }
        public long OrgId { get; set; }
        public long CallerId { get; set; }
        public Nullable<long> SolverTeamId { get; set; }
        public Nullable<long> SolverId { get; set; }
        public long StatusId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> ResolveDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string TicketLog { get; set; }
        public Nullable<long> ResolutionId { get; set; }
        public string ResolutionDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident> Incident { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Team Team { get; set; }
        public virtual Resolution Resolution { get; set; }
        public virtual TicketStatus TicketStatus { get; set; }
        public virtual TicketType TicketType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRequest> UserRequest { get; set; }
    }
}
