//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Implementation.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTransition
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public long StatusFromId { get; set; }
        public long StatusToId { get; set; }
        public long TicketTypeId { get; set; }
    
        public virtual TicketStatus TicketStatus { get; set; }
        public virtual TicketStatus TicketStatus1 { get; set; }
        public virtual TicketType TicketType { get; set; }
    }
}
