//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Implementation.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRequest
    {
        public long Id { get; set; }
        public long TicketId { get; set; }
        public int Priority { get; set; }
        public int Urgency { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
