//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Implementation.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.LnkRoleToUser = new HashSet<LnkRoleToUser>();
        }
    
        public long Id { get; set; }
        public bool ActiveStatus { get; set; }
        public long PersonId { get; set; }
        public long OrgId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LnkRoleToUser> LnkRoleToUser { get; set; }
    }
}
